version: '3.2'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - 81:8080
    volumes:
      - .:/var/www/app
    #environment:
  # nginx
  # mysql
#  mysql:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=verysecret
#      - MYSQL_DATABASE=yii2advanced
#      - MYSQL_USER=yii2advanced
#      - MYSQL_PASSWORD=secret