<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adresa' => '',
    'Adresa 1' => '',
    'Adresa 2 (voliteľné)' => '',
    'Akademický titul' => '',
    'Cestovný pas' => '',
    'Dokumenty' => 'Dokumentumok',
    'Doplňujúce informácie' => '',
    'Dátum narodenia' => '',
    'Email' => '',
    'Expert (C2)' => '',
    'Fotografia' => '',
    'Heslo' => '',
    'Jazykové znalosti' => '',
    'Kontaktná adresa/prechodné bydlisko' => '',
    'Kontaktné údaje' => '',
    'Krajina' => '',
    'Materinský jazyk' => '',
    'Meno' => '',
    'Mesto' => '',
    'Mierne pokročilý (B1)' => '',
    'Miesto narodenia' => '',
    'Muž' => '',
    'Nahrať' => '',
    'Najvyššie dosiahnuté vzdelanie' => '',
    'Občiansky preukaz' => '',
    'Osobné údaje' => '',
    'Ostatné znalosti' => '',
    'PSČ' => '',
    'Platnosť' => '',
    'Pohlavie' => '',
    'Pokročilý (C1)' => '',
    'Popis práce (nepovinné)' => '',
    'Pracovné skúsenosti' => '',
    'Predná strana' => '',
    'Pridať kurz' => '',
    'Pridať pracovnú pozíciu' => '',
    'Pridať strednú školu' => '',
    'Pridať vysokú školu' => '',
    'Priezvisko' => '',
    'Profesia' => '',
    'Registrácia' => '',
    'Rodné priezvisko' => '',
    'Rodné číslo' => '',
    'Služby' => '',
    'Spracovávam nahraté dokumenty...' => '',
    'Späť' => '',
    'Stredne pokročilý (B2)' => '',
    'Telefón' => '',
    'Trvalé bydlisko' => '',
    'Vodičský preukaz' => '',
    'Vyberte úroveň' => '',
    'Vydal' => '',
    'Vydané dňa' => '',
    'Vzdelanie' => '',
    'Zadná strana' => '',
    'Zamestnaný do' => '',
    'Zamestnaný od' => '',
    'Zamestnávateľ' => '',
    'Začiatočník (A2)' => '',
    'Začnite posledným zamestnaním. Uveďte aj dobrovoľnícke aktivity, študentské stáže, prax atď.' => '',
    'Zmazať' => '',
    'Zopkovať heslo' => '',
    'Zrušiť' => '',
    'Zvoľte krajinu' => '',
    'Zvoľte si pohlavie' => '',
    'Zvoľte titul' => '',
    'nadstavbové/vyššie odborné vzdelanie' => '',
    'stredoškolské bez maturity' => '',
    'stredoškolské s maturitou' => '',
    'vysokoškolské I. stupňa' => '',
    'vysokoškolské II. stupňa' => '',
    'vysokoškolské III. stupňa' => '',
    'základné vzdelanie' => '',
    'Úplný začiatočník (A1)' => '',
    'Číslo OP' => '',
    'Ďalej' => '',
    'Ďalšie informácie' => '',
    'Ďalšie schopnosti a znalosti' => '',
    'Školy a kurzy' => '',
    'študent strednej školy' => '',
    'študent vysokej školy' => '',
    'Žena' => '',
];
